CREATE SCHEMA IF NOT EXISTS DEMO_DB.RAW;

CREATE OR REPLACE TABLE DEMO_DB.RAW.USER_SESSION_CHANNEL (
    userId INT NOT NULL,
    sessionId VARCHAR(32) PRIMARY KEY,
    channel VARCHAR(32) DEFAULT 'direct'
);

CREATE OR REPLACE TABLE DEMO_DB.RAW.SESSION_TIMESTAMP (
    sessionId VARCHAR(32) PRIMARY KEY,
    ts TIMESTAMP
);

CREATE OR REPLACE STAGE DEMO_DB.RAW.BLOB_STAGE
    URL = 's3://s3-geospatial/readonly/'
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    );

COPY INTO DEMO_DB.RAW.USER_SESSION_CHANNEL
FROM @DEMO_DB.RAW.BLOB_STAGE/user_session_channel.csv;

COPY INTO DEMO_DB.RAW.SESSION_TIMESTAMP
FROM @DEMO_DB.RAW.BLOB_STAGE/session_timestamp.csv;
